from enum import StrEnum


class ProjectStage(StrEnum):
    PROJECT_INTAKE = "PROJECT_INTAKE"
    REQUIREMENT_CONFIRMATION = "REQUIREMENT_CONFIRMATION"
    SOLUTION_DESIGN = "SOLUTION_DESIGN"
    CUSTOMER_VISIT_MATERIALS = "CUSTOMER_VISIT_MATERIALS"
    DEMO_AND_POC = "DEMO_AND_POC"
    BUDGET_APPROVAL = "BUDGET_APPROVAL"
    BIDDING_CONTROL = "BIDDING_CONTROL"
    BID_RESPONSE = "BID_RESPONSE"
    CONTRACT_HANDOVER = "CONTRACT_HANDOVER"
    PROJECT_RETROSPECTIVE = "PROJECT_RETROSPECTIVE"


class ProjectStatus(StrEnum):
    ACTIVE = "ACTIVE"
    ON_HOLD = "ON_HOLD"
    WON = "WON"
    LOST = "LOST"
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"


class ActivityType(StrEnum):
    CUSTOMER_VISIT = "CUSTOMER_VISIT"
    PHONE_CALL = "PHONE_CALL"
    WECHAT_COMMUNICATION = "WECHAT_COMMUNICATION"
    MEETING = "MEETING"
    INTERNAL_DISCUSSION = "INTERNAL_DISCUSSION"
    EMAIL = "EMAIL"
    DOCUMENT_REVIEW = "DOCUMENT_REVIEW"
    POC_ACTIVITY = "POC_ACTIVITY"
    BID_ACTIVITY = "BID_ACTIVITY"
    MANUAL_NOTE = "MANUAL_NOTE"
    OTHER = "OTHER"


class SourceType(StrEnum):
    MANUAL = "MANUAL"
    OBSIDIAN = "OBSIDIAN"
    EMAIL = "EMAIL"
    CALENDAR = "CALENDAR"
    MEETING_TRANSCRIPT = "MEETING_TRANSCRIPT"
    DOCUMENT = "DOCUMENT"
    WECHAT = "WECHAT"
    API = "API"
    OTHER = "OTHER"


class ExtractionStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSED = "PROCESSED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class RequirementStatus(StrEnum):
    OPEN = "OPEN"
    CONFIRMED = "CONFIRMED"
    CHANGED = "CHANGED"
    SATISFIED = "SATISFIED"
    REJECTED = "REJECTED"
    UNKNOWN = "UNKNOWN"


class OwnerType(StrEnum):
    SELF = "SELF"
    CUSTOMER = "CUSTOMER"
    TEAM = "TEAM"
    SALES = "SALES"
    PARTNER = "PARTNER"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class TaskStatus(StrEnum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    BLOCKED = "BLOCKED"
    DONE = "DONE"
    CANCELLED = "CANCELLED"
    UNKNOWN = "UNKNOWN"


class RiskSeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    UNKNOWN = "UNKNOWN"


class RiskStatus(StrEnum):
    OPEN = "OPEN"
    MONITORING = "MONITORING"
    MITIGATED = "MITIGATED"
    RESOLVED = "RESOLVED"
    ACCEPTED = "ACCEPTED"
    UNKNOWN = "UNKNOWN"


class Priority(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
